---
version: '3.8'
services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    # FIX 1: Run the container as the root user to solve the volume permission issue.
    user: root
    ports: [9092:9092]
    volumes: [kafka_data:/tmp/kafka-logs]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ciWo7IWazngRchmPES6q5A
  connect:
    image: apache/kafka:latest
    container_name: connect
    ports: [8083:8083]
    volumes:
      - ./data:/data
      - ./scripts:/scripts
      # FIX 2: Mount the new properties file to configure the worker correctly.
      - ./connect/connect-distributed.properties:/opt/kafka/config/connect-distributed.properties
    depends_on:
      - kafka
    # FIX 2: Removed the non-functional 'environment' block and replaced the
    # command with the correct script and path to the properties file.
    command: /opt/kafka/bin/connect-distributed.sh /opt/kafka/config/connect-distributed.properties
  init-connectors:
    image: curlimages/curl:latest
    container_name: init-connectors
    depends_on: [connect]
    volumes: [./scripts:/scripts]
    command: >
      sh -c "
        chmod +x /scripts/init-connectors.sh &&
        /scripts/init-connectors.sh
      "
volumes:
  kafka_data:
    driver: local
