---
services:
  #
  # KAFKA CONNECT
  #
  postgres:
    image: postgres:latest
    container_name: postgres
    ports: [5432:5432]
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: |
      postgres 
      -c wal_level=logical
      -c max_wal_senders=1
      -c max_replication_slots=1
  #
  # KAFKA BROKER
  # 
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: root
    ports: [9092:9092, 9093:9093]
    # volumes: [kafka_data:/tmp/kafka-logs]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /tmp/kafka-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: ciWo7IWazngRchmPES6q5A
  #
  # KAFKA CONNECT
  #
  connect:
    build:
      context: .
      dockerfile: Dockerfile.connect
    container_name: connect
    ports: [8083:8083]
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_PORT: 8082
      CONNECT_GROUP_ID: '1'
      CONNECT_CONFIG_STORAGE_TOPIC: config
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_TOPIC: offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
    depends_on:
      - kafka
  #
  # INIT CONNECTORS
  #
  init-connectors:
    image: curlimages/curl:latest
    container_name: init-connectors
    depends_on: [connect]
    volumes: [./scripts:/scripts]
    command: >
      sh -c "
        chmod +x /scripts/init-connectors.sh &&
        /scripts/init-connectors.sh
      "
volumes:
  kafka_data:
    driver: local
